name: CI

on:
#   push:
#    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python Requirements
        run: make init

      - name: Lint everything
        run: make lint
        
      - name: Run tests
        run: make test

  run:
    needs: test
    runs-on: ubuntu-latest
    environment: run
    steps:
      - uses: actions/checkout@v2

      - name: Install Python Requirements
        run: make init

      - name: Export Calendar
        run: make run
        env:
          GOOGLE_API_TOKEN: ${{ secrets.GOOGLE_API_TOKEN }}
          GOOGLE_API_REFRESH_TOKEN: ${{ secrets.GOOGLE_API_REFRESH_TOKEN }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
